- id: 1
  name: 日本ハム
  key: 'fighters'
  order: 1
- id: 2
  name: ソフトバンク
  key: 'hawks'
  order: 2
- id: 3
  name: ロッテ
  key: 'marines'
  order: 3
- id: 4
  name: 西武
  key: 'lions'
  order: 4
- id: 5
  name: 楽天
  key: 'eagles'
  order: 5
- id: 6
  name: オリックス
  key: 'buffaloes'
  order: 6
- id: 7
  name: 広島
  key: 'carp'
  order: 7
- id: 8
  name: 巨人
  key: 'giants'
  order: 8
- id: 9
  name: DeNA
  key: 'baystars'
  order: 9
- id: 10
  name: 阪神
  key: 'tigers'
  order: 10
- id: 11
  name: ヤクルト
  key: 'swallows'
  order: 11
- id: 12
  name: 中日
  key: 'dragons'
  order: 12
